name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build-prod

      - name: Deploy Firebase Site
        # You may pin to the exact commit or the version.
        # uses: danielmillan/pipelines-firebase-hosting@8a7c15d150288fde37efe3edb186e5bb5931c3de
        uses: danielmillan/pipelines-firebase-hosting@1.0.8
        with:
          # Token generated to authenticate in firebase
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          # Name of the folder containing the resources to be deployed
          resources-name: www
          # Firebase project name
          project-name: douglaswhite-app
